//
// Created by fanz on 9/6/17.
//

#ifndef PARALYSIS_PROOF_ERRNO_H
#define PARALYSIS_PROOF_ERRNO_H

#define SECRETKEY_SEALED_LEN 1024
#define SECKEY_LEN  32
#define PUBKEY_LEN  65
#define ADDRESS_LEN 20

#define HYBRID_KEY_NOT_PROVISIONED  -0x9001
#define RSA_KEY_NOT_PROVISIONED     -0x9002
#define BUFFER_TOO_SMALL            -0x8001

#endif //PARALYSIS_PROOF_ERRNO_H
